---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance
    memory: 64
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: testinfra
lint: |
  set -e
  ansible-lint