---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    options:
      memory: 128
      cpus: 1
    driver: kvm
platforms:
  - name: instance
    box: generic/alpine38
provisioner:
  name: ansible
verifier:
  name: testinfra
lint: |
  set -e
  ansible-lint