- hosts: localhost,
  tasks:
    - name: Create CA folder
      file:
        path: files/ca
        recurse: true
        mode: 0775
        state: directory
    - name: Create CA
      command: ssh-keygen -f files/ca/ca creates=files/ca/ca
- hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Install python # noqa 301
      raw: apk add --update --no-cache python3